- name: Install Zabbix Server
  hosts: zabbix
  become: true

  tasks:
    - name: Install repo
      command: rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
      ignore_errors: yes

    - name: Install requir ed packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - httpd
        - zabbix-apache-conf
        - zabbix-sql-scripts 
        - zabbix-selinux-policy
        - zabbix-server-mysql
        - zabbix-web-mysql
        - mariadb
        - mariadb-server

    - name: Start and enable Zabbix agent
      service:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: Start and enable Web Server
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Start and enable zabbix Server
      service:
        name: zabbix-server
        state: started
        enabled: no
    
    - name: Start and enable Database
      service:
        name: mariadb
        state: started
        enabled: yes

